name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.8

      - name: Compile
        run: sbt compile

      - name: Test
        run: sbt test
